[package]
name = "mdai"
description = "Releaser for mdai-cli"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/decisiveai/mdai-cli"
homepage = "https://www.mydecisive.ai/"
binaries = ["mdai"]
build-command = ["make", "ci-build"]

[package.metadata.wix]
upgrade-guid = "9A4352DB-B302-4E7A-BFBD-DAD056AD6A34"
path-guid = "B86F05C3-D50F-4B12-A5FC-D508854ECAF5"
license = false
eula = false

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.14.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
# A GitHub repo to push Homebrew formulas to
tap = "decisiveai/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
# Path that installers should place binaries in
install-path = ["$MDAI_CLI_HOME/bin", "~/.mdai/bin"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
