admissionWebhooks:
  certManager:
    enabled: false
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.101.0
  leaderElection:
    enabled: false
  env:
    ENABLE_WEBHOOKS: "true"
kubeRBACProxy:
  enabled: false