apiVersion: v1
clusters:
- cluster:
    server: %s
    certificate-authority-data: %s
    disable-compression: true
  name: %s
contexts:
- context:
    cluster: %s
    user: aws
  name: eks-context
current-context: eks-context
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - %s
      command: aws-iam-authenticator
      env: null