admissionWebhooks:
  certManager:
    enabled: false
manager:
#  image:
#    repository: public.ecr.aws/p3k6k6h3/opentelemetry-operator
#    tag: latest
  collectorImage:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.101.0
  leaderElection:
    enabled: false
  env:
    ENABLE_WEBHOOKS: "true"
kubeRBACProxy:
  enabled: false
