apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
    name: test-collector
    namespace: default
spec:
    replicas: 2
    resources:
        limits:
            cpu: 500m
        requests:
            cpu: 250m
    upgradeStrategy: automatic
    mode: deployment
    configVersions: 5
    config:
        receivers:
          otlp:
            protocols:
              http:
                endpoint: 0.0.0.0:4318
              grpc:
          jaeger:
            protocols:
              grpc:
          hostmetrics:
            collection_interval: 13s
            scrapers:
              load:
              filesystem:
              memory:
              network:
              paging:
              process:
              processes:
        processors:
          memory_limiter:
            check_interval: 13s
            limit_percentage: 75
            spike_limit_percentage: 15
          batch:
            send_batch_size: 10000
            timeout: 13s
        exporters:
          debug:
        service:
          pipelines:
            traces:
              receivers: [jaeger, otlp]
              processors: [memory_limiter, batch]
              exporters: [debug]
            metrics:
              receivers: [hostmetrics, otlp]
              processors: [batch]
              exporters: [debug]
            logs:
              receivers: [otlp]
              processors: [batch]
              exporters: [debug]
